import pygame

# Constants - Retro CRT Color Scheme
# Base resolution (will be scaled)
BASE_WIDTH = 640
BASE_HEIGHT = 586

FPS = 30

# Retro green phosphor CRT colors
CRT_BLACK = (20, 24, 20)
CRT_GREEN = (51, 255, 51)
CRT_GREEN_DIM = (20, 120, 20)
CRT_GREEN_BRIGHT = (102, 255, 102)
CRT_AMBER = (255, 176, 0)
CRT_AMBER_DIM = (153, 102, 0)

# Alternative retro palette
RETRO_BG = (12, 26, 24)
RETRO_BLUE = (76, 132, 255)
RETRO_PINK = (255, 89, 157)
RETRO_PURPLE = (138, 68, 255)
RETRO_CYAN = (51, 255, 219)
RETRO_WHITE = (230, 230, 230)
RETRO_GREEN = (102, 255, 102)
RETRO_RED = (255, 89, 89)
RETRO_YELLOW = (255, 234, 89)

# Game colors (retro theme)
BG_COLOR = RETRO_BG
TEXT_COLOR = RETRO_CYAN
TITLE_COLOR = RETRO_PINK
TITLE_COLOR2 = RETRO_CYAN
INPUT_BG = (40, 35, 60)
INPUT_TEXT = RETRO_WHITE
CORRECT_COLOR = RETRO_GREEN
INCORRECT_COLOR = RETRO_RED
STATS_COLOR = RETRO_YELLOW
BUTTON_COLOR = RETRO_PURPLE
BUTTON_HOVER = RETRO_PINK

# Scanline effect
SCANLINE_ALPHA = 30
SCANLINE_SPACING = 3

# UI Geometry - All rect definitions in one place
# Buttons
BUTTON_W = 80
BUTTON_H = 32
BUTTON_RESET = pygame.Rect(BASE_WIDTH - BUTTON_W*2 - 8, 4, BUTTON_W, BUTTON_H)
BUTTON_SCORES = pygame.Rect(BASE_WIDTH - BUTTON_W - 4, 4, BUTTON_W, BUTTON_H)
BUTTON_BACK = pygame.Rect(BASE_WIDTH - BUTTON_W - 4, 4, BUTTON_W, BUTTON_H)

# Input box
INPUT_BOX_WIDTH = BASE_WIDTH - 36
INPUT_BOX_HEIGHT = 64
INPUT_BOX_X = (BASE_WIDTH - INPUT_BOX_WIDTH) // 2
INPUT_BOX_Y = 480
INPUT_BOX = pygame.Rect(INPUT_BOX_X, INPUT_BOX_Y, INPUT_BOX_WIDTH, INPUT_BOX_HEIGHT)

# Timer
TIMER_Y = 72
TIMER_WIDTH = 164
TIMER_HEIGHT = 64
TIMER_RECT = pygame.Rect(BASE_WIDTH - BUTTON_W*2 - 8, TIMER_Y - 32, TIMER_WIDTH, TIMER_HEIGHT)

# Game over overlay
GAME_OVER_BOX_WIDTH = 400
GAME_OVER_BOX_HEIGHT = 240
GAME_OVER_BOX_X = (BASE_WIDTH - GAME_OVER_BOX_WIDTH) // 2
GAME_OVER_BOX_Y = (BASE_HEIGHT - GAME_OVER_BOX_HEIGHT) // 2
GAME_OVER_BOX = pygame.Rect(GAME_OVER_BOX_X, GAME_OVER_BOX_Y, GAME_OVER_BOX_WIDTH, GAME_OVER_BOX_HEIGHT)

# Y positions
TITLE_Y = 2
ROAD_START_Y = 430
ROAD_SPACING_Y = 54
STATS_Y = 560
SCORES_HEADER_Y = 100
SCORES_LIST_X = 100
SCORES_LIST_Y = 150